#ifndef OS_UNIX_BROWNIAN_SERVER_BOT_CONFIG_READING_H
#define OS_UNIX_BROWNIAN_SERVER_BOT_CONFIG_READING_H

const char * getSocketNameFromConfig(const char * configName);

#endif //OS_UNIX_BROWNIAN_SERVER_BOT_CONFIG_READING_H
